## Groupby Operations in Pandas

### The Split - Apply - Combine method

http://pandas.pydata.org/pandas-docs/stable/groupby.html

* Split :  groupby()
* Apply : aggregate, transform, filter
* Combine : combine results

In [30]:
%matplotlib inline

import matplotlib

matplotlib.style.use('fivethirtyeight')

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
# Import the IRIS dataset from the csv file

irisdf = pd.read_csv('iris.csv')

irisdf.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
irisdf.columns

Index([u'sepal_length', u'sepal_width', u'petal_length', u'petal_width',
       u'species'],
      dtype='object')

In [5]:
# How many species are there in the dataset?

set(irisdf.species)

{'setosa', 'versicolor', 'virginica'}

## Split Operation using GROUPBY

In [6]:
# Let us group by species so we can get interesting information

irisdf.groupby('species')

In [7]:
# Let us iterate through this object 

irisgroup = irisdf.groupby('species')

irisgroup.indices

{'setosa': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], dtype=int64),
 'versicolor': array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64),
 'virginica': array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149], dtype=int64)}

In [8]:
irisgroup.indices.keys()

['setosa', 'versicolor', 'virginica']

In [9]:
irisgroup.indices.values()

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], dtype=int64),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149], dtype=int64)]

In [14]:
# Ok lets iterate this then! 

for k, v in irisgroup:
    print '\n\n----New Group Starts-----\n\n'
    print k
    print v
    print '\n\n----New Group Ends-----\n\n'

----New Group Starts-----


setosa
    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa


----New Group Ends-----




----New Group Starts-----


versicolor
    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor


----New Group Ends-----




----New Group Starts-----


virginica
     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


----New Group Ends-----

In [19]:
# Another way to look at a groupby object 

list(irisgroup)

[('setosa',     sepal_length  sepal_width  petal_length  petal_width species
  0            5.1          3.5           1.4          0.2  setosa
  1            4.9          3.0           1.4          0.2  setosa
  2            4.7          3.2           1.3          0.2  setosa
  3            4.6          3.1           1.5          0.2  setosa
  4            5.0          3.6           1.4          0.2  setosa
  5            5.4          3.9           1.7          0.4  setosa
  6            4.6          3.4           1.4          0.3  setosa
  7            5.0          3.4           1.5          0.2  setosa
  8            4.4          2.9           1.4          0.2  setosa
  9            4.9          3.1           1.5          0.1  setosa
  10           5.4          3.7           1.5          0.2  setosa
  11           4.8          3.4           1.6          0.2  setosa
  12           4.8          3.0           1.4          0.1  setosa
  13           4.3          3.0           1.1          0.1  setosa
  14           5.8          4.0           1.2          0.2  setosa
  15           5.7          4.4           1.5          0.4  setosa
  16           5.4          3.9           1.3          0.4  setosa
  17           5.1          3.5           1.4          0.3  setosa
  18           5.7          3.8           1.7          0.3  setosa
  19           5.1          3.8           1.5          0.3  setosa
  20           5.4          3.4           1.7          0.2  setosa
  21           5.1          3.7           1.5          0.4  setosa
  22           4.6          3.6           1.0          0.2  setosa
  23           5.1          3.3           1.7          0.5  setosa
  24           4.8          3.4           1.9          0.2  setosa
  25           5.0          3.0           1.6          0.2  setosa
  26           5.0          3.4           1.6          0.4  setosa
  27           5.2          3.5           1.5          0.2  setosa
  28           5.2          3.4           1.4          0.2  setosa
  29           4.7          3.2           1.6          0.2  setosa
  30           4.8          3.1           1.6          0.2  setosa
  31           5.4          3.4           1.5          0.4  setosa
  32           5.2          4.1           1.5          0.1  setosa
  33           5.5          4.2           1.4          0.2  setosa
  34           4.9          3.1           1.5          0.1  setosa
  35           5.0          3.2           1.2          0.2  setosa
  36           5.5          3.5           1.3          0.2  setosa
  37           4.9          3.1           1.5          0.1  setosa
  38           4.4          3.0           1.3          0.2  setosa
  39           5.1          3.4           1.5          0.2  setosa
  40           5.0          3.5           1.3          0.3  setosa
  41           4.5          2.3           1.3          0.3  setosa
  42           4.4          3.2           1.3          0.2  setosa
  43           5.0          3.5           1.6          0.6  setosa
  44           5.1          3.8           1.9          0.4  setosa
  45           4.8          3.0           1.4          0.3  setosa
  46           5.1          3.8           1.6          0.2  setosa
  47           4.6          3.2           1.4          0.2  setosa
  48           5.3          3.7           1.5          0.2  setosa
  49           5.0          3.3           1.4          0.2  setosa),
 ('versicolor',
      sepal_length  sepal_width  petal_length  petal_width     species
  50           7.0          3.2           4.7          1.4  versicolor
  51           6.4          3.2           4.5          1.5  versicolor
  52           6.9          3.1           4.9          1.5  versicolor
  53           5.5          2.3           4.0          1.3  versicolor
  54           6.5          2.8           4.6          1.5  versicolor
  55           5.7          2.8           4.5          1.3  versicolor
  56           6.3          3.3           4.7          1.6  versicolor
  57           4.9          2.4           3.3          1.0  versicolor
  58           6.6          2.9           4.6          1.3  versicolor
  59           5.2          2.7           3.9          1.4  versicolor
  60           5.0          2.0           3.5          1.0  versicolor
  61           5.9          3.0           4.2          1.5  versicolor
  62           6.0          2.2           4.0          1.0  versicolor
  63           6.1          2.9           4.7          1.4  versicolor
  64           5.6          2.9           3.6          1.3  versicolor
  65           6.7          3.1           4.4          1.4  versicolor
  66           5.6          3.0           4.5          1.5  versicolor
  67           5.8          2.7           4.1          1.0  versicolor
  68           6.2          2.2           4.5          1.5  versicolor
  69           5.6          2.5           3.9          1.1  versicolor
  70           5.9          3.2           4.8          1.8  versicolor
  71           6.1          2.8           4.0          1.3  versicolor
  72           6.3          2.5           4.9          1.5  versicolor
  73           6.1          2.8           4.7          1.2  versicolor
  74           6.4          2.9           4.3          1.3  versicolor
  75           6.6          3.0           4.4          1.4  versicolor
  76           6.8          2.8           4.8          1.4  versicolor
  77           6.7          3.0           5.0          1.7  versicolor
  78           6.0          2.9           4.5          1.5  versicolor
  79           5.7          2.6           3.5          1.0  versicolor
  80           5.5          2.4           3.8          1.1  versicolor
  81           5.5          2.4           3.7          1.0  versicolor
  82           5.8          2.7           3.9          1.2  versicolor
  83           6.0          2.7           5.1          1.6  versicolor
  84           5.4          3.0           4.5          1.5  versicolor
  85           6.0          3.4           4.5          1.6  versicolor
  86           6.7          3.1           4.7          1.5  versicolor
  87           6.3          2.3           4.4          1.3  versicolor
  88           5.6          3.0           4.1          1.3  versicolor
  89           5.5          2.5           4.0          1.3  versicolor
  90           5.5          2.6           4.4          1.2  versicolor
  91           6.1          3.0           4.6          1.4  versicolor
  92           5.8          2.6           4.0          1.2  versicolor
  93           5.0          2.3           3.3          1.0  versicolor
  94           5.6          2.7           4.2          1.3  versicolor
  95           5.7          3.0           4.2          1.2  versicolor
  96           5.7          2.9           4.2          1.3  versicolor
  97           6.2          2.9           4.3          1.3  versicolor
  98           5.1          2.5           3.0          1.1  versicolor
  99           5.7          2.8           4.1          1.3  versicolor),
 ('virginica',
       sepal_length  sepal_width  petal_length  petal_width    species
  100           6.3          3.3           6.0          2.5  virginica
  101           5.8          2.7           5.1          1.9  virginica
  102           7.1          3.0           5.9          2.1  virginica
  103           6.3          2.9           5.6          1.8  virginica
  104           6.5          3.0           5.8          2.2  virginica
  105           7.6          3.0           6.6          2.1  virginica
  106           4.9          2.5           4.5          1.7  virginica
  107           7.3          2.9           6.3          1.8  virginica
  108           6.7          2.5           5.8          1.8  virginica
  109           7.2          3.6           6.1          2.5  virginica
  110           6.5          3.2           5.1          2.0  virginica
  111           6.4          2.7           5.3          1.9  virginica
  112           6.8          3.0           5.5          2.1  virginica
  113           5.7          2.5           5.0          2.0  virginica
  114           5.8          2.8           5.1          2.4  virginica
  115           6.4          3.2           5.3          2.3  virginica
  116           6.5          3.0           5.5          1.8  virginica
  117           7.7          3.8           6.7          2.2  virginica
  118           7.7          2.6           6.9          2.3  virginica
  119           6.0          2.2           5.0          1.5  virginica
  120           6.9          3.2           5.7          2.3  virginica
  121           5.6          2.8           4.9          2.0  virginica
  122           7.7          2.8           6.7          2.0  virginica
  123           6.3          2.7           4.9          1.8  virginica
  124           6.7          3.3           5.7          2.1  virginica
  125           7.2          3.2           6.0          1.8  virginica
  126           6.2          2.8           4.8          1.8  virginica
  127           6.1          3.0           4.9          1.8  virginica
  128           6.4          2.8           5.6          2.1  virginica
  129           7.2          3.0           5.8          1.6  virginica
  130           7.4          2.8           6.1          1.9  virginica
  131           7.9          3.8           6.4          2.0  virginica
  132           6.4          2.8           5.6          2.2  virginica
  133           6.3          2.8           5.1          1.5  virginica
  134           6.1          2.6           5.6          1.4  virginica
  135           7.7          3.0           6.1          2.3  virginica
  136           6.3          3.4           5.6          2.4  virginica
  137           6.4          3.1           5.5          1.8  virginica
  138           6.0          3.0           4.8          1.8  virginica
  139           6.9          3.1           5.4          2.1  virginica
  140           6.7          3.1           5.6          2.4  virginica
  141           6.9          3.1           5.1          2.3  virginica
  142           5.8          2.7           5.1          1.9  virginica
  143           6.8          3.2           5.9          2.3  virginica
  144           6.7          3.3           5.7          2.5  virginica
  145           6.7          3.0           5.2          2.3  virginica
  146           6.3          2.5           5.0          1.9  virginica
  147           6.5          3.0           5.2          2.0  virginica
  148           6.2          3.4           5.4          2.3  virginica
  149           5.9          3.0           5.1          1.8  virginica)]

In [26]:
irisgroup.groups

{'setosa': [0L,
  1L,
  2L,
  3L,
  4L,
  5L,
  6L,
  7L,
  8L,
  9L,
  10L,
  11L,
  12L,
  13L,
  14L,
  15L,
  16L,
  17L,
  18L,
  19L,
  20L,
  21L,
  22L,
  23L,
  24L,
  25L,
  26L,
  27L,
  28L,
  29L,
  30L,
  31L,
  32L,
  33L,
  34L,
  35L,
  36L,
  37L,
  38L,
  39L,
  40L,
  41L,
  42L,
  43L,
  44L,
  45L,
  46L,
  47L,
  48L,
  49L],
 'versicolor': [50L,
  51L,
  52L,
  53L,
  54L,
  55L,
  56L,
  57L,
  58L,
  59L,
  60L,
  61L,
  62L,
  63L,
  64L,
  65L,
  66L,
  67L,
  68L,
  69L,
  70L,
  71L,
  72L,
  73L,
  74L,
  75L,
  76L,
  77L,
  78L,
  79L,
  80L,
  81L,
  82L,
  83L,
  84L,
  85L,
  86L,
  87L,
  88L,
  89L,
  90L,
  91L,
  92L,
  93L,
  94L,
  95L,
  96L,
  97L,
  98L,
  99L],
 'virginica': [100L,
  101L,
  102L,
  103L,
  104L,
  105L,
  106L,
  107L,
  108L,
  109L,
  110L,
  111L,
  112L,
  113L,
  114L,
  115L,
  116L,
  117L,
  118L,
  119L,
  120L,
  121L,
  122L,
  123L,
  124L,
  125L,
  126L,
  127L,
  128L,
  129L,
  130L,
  131L,
  132L,
  133L,
  134L,
  135L,
  136L,
  137L,
  138L,
  139L,
  140L,
  141L,
  142L,
  143L,
  144L,
  145L,
  146L,
  147L,
  148L,
  149L]}

In [28]:
irisgroup.get_group('setosa')

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

## Apply - Combine Operations

### Aggregation Techniques:  summary statistics

In [15]:
irisgroup.sepal_length

In [20]:
irisgroup.sepal_length.mean()

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal_length, dtype: float64

In [21]:
irisgroup['sepal_length', 'petal_width'].mean()

            sepal_length  petal_width
species
setosa             5.006        0.244
versicolor         5.936        1.326
virginica          6.588        2.026

In [22]:
# Lets transpose this! 

irisgroup['sepal_length', 'petal_width'].mean().T

species       setosa  versicolor  virginica
sepal_length   5.006       5.936      6.588
petal_width    0.244       1.326      2.026

In [31]:
irisgroup.aggregate(np.mean)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [32]:
irisgroup.agg(np.sum)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [33]:
irisgroup.agg([np.sum, np.mean])

           sepal_length        sepal_width        petal_length         \
                    sum   mean         sum   mean          sum   mean
species
setosa            250.3  5.006       170.9  3.418         73.2  1.464
versicolor        296.8  5.936       138.5  2.770        213.0  4.260
virginica         329.4  6.588       148.7  2.974        277.6  5.552

           petal_width
                   sum   mean
species
setosa            12.2  0.244
versicolor        66.3  1.326
virginica        101.3  2.026

In [34]:
irisgroup.agg([np.sum, np.mean]).columns

MultiIndex(levels=[[u'sepal_length', u'sepal_width', u'petal_length', u'petal_width'], [u'sum', u'mean']],
           labels=[[0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1]])

In [35]:
irisgroup.agg([np.sum, np.mean]).unstack()

                    species
sepal_length  sum   setosa        250.300
                    versicolor    296.800
                    virginica     329.400
              mean  setosa          5.006
                    versicolor      5.936
                    virginica       6.588
sepal_width   sum   setosa        170.900
                    versicolor    138.500
                    virginica     148.700
              mean  setosa          3.418
                    versicolor      2.770
                    virginica       2.974
petal_length  sum   setosa         73.200
                    versicolor    213.000
                    virginica     277.600
              mean  setosa          1.464
                    versicolor      4.260
                    virginica       5.552
petal_width   sum   setosa         12.200
                    versicolor     66.300
                    virginica     101.300
              mean  setosa          0.244
                    versicolor      1.326
                    virginica       2.026
dtype: float64

In [36]:
irisgroup.agg([np.min, np.max, np.mean])

           sepal_length             sepal_width             petal_length       \
                   amin amax   mean        amin amax   mean         amin amax
species
setosa              4.3  5.8  5.006         2.3  4.4  3.418          1.0  1.9
versicolor          4.9  7.0  5.936         2.0  3.4  2.770          3.0  5.1
virginica           4.9  7.9  6.588         2.2  3.8  2.974          4.5  6.9

                  petal_width
             mean        amin amax   mean
species
setosa      1.464         0.1  0.6  0.244
versicolor  4.260         1.0  1.8  1.326
virginica   5.552         1.4  2.5  2.026

In [38]:
irisgroup['sepal_length'].agg({
        'minimum' : np.min,
        'mean' : np.mean,
        'maximum' : np.max
    })

            minimum  maximum   mean
species
setosa          4.3      5.8  5.006
versicolor      4.9      7.0  5.936
virginica       4.9      7.9  6.588

In [39]:
irisgroup['sepal_length'].agg({
        'minimum' : np.min,
        'mean' : np.mean,
        'maximum' : np.max,
        'maxrange' : lambda x: np.max(x) - np.min(x)
    })

            maxrange  minimum  maximum   mean
species
setosa           1.5      4.3      5.8  5.006
versicolor       2.1      4.9      7.0  5.936
virginica        3.0      4.9      7.9  6.588

## Apply - Combine Operations

### Transformation Techniques
http://pandas.pydata.org/pandas-docs/stable/groupby.html#transformation

Important points to remember from the documentation:

* The transform method returns an object that is indexed the same (same size) as the one being grouped
* Thus, the passed transform function should return a result that is the same size as the group chunk

In [56]:
zscore = lambda x: (x - x.mean()) / x.std()

irisgroup.transform(zscore)

     sepal_length  sepal_width  petal_length  petal_width
0        0.266674     0.215209     -0.368852    -0.410411
1       -0.300718    -1.097043     -0.368852    -0.410411
2       -0.868111    -0.572142     -0.945184    -0.410411
3       -1.151807    -0.834592      0.207479    -0.410411
4       -0.017022     0.477660     -0.368852    -0.410411
5        1.117763     1.265011      1.360143     1.455095
6       -1.151807    -0.047241     -0.368852     0.522342
7       -0.017022    -0.047241      0.207479    -0.410411
8       -1.719199    -1.359493     -0.368852    -0.410411
9       -0.300718    -0.834592      0.207479    -1.343165
10       1.117763     0.740110      0.207479    -0.410411
11      -0.584414    -0.047241      0.783811    -0.410411
12      -0.584414    -1.097043     -0.368852    -1.343165
13      -2.002895    -1.097043     -2.097848    -1.343165
14       2.252548     1.527461     -1.521516    -0.410411
15       1.968852     2.577263      0.207479     1.455095
16       1.117763     1.265011     -0.945184     1.455095
17       0.266674     0.215209     -0.368852     0.522342
18       1.968852     1.002560      1.360143     0.522342
19       0.266674     1.002560      0.207479     0.522342
20       1.117763    -0.047241      1.360143    -0.410411
21       0.266674     0.740110      0.207479     1.455095
22      -1.151807     0.477660     -2.674180    -0.410411
23       0.266674    -0.309691      1.360143     2.387848
24      -0.584414    -0.047241      2.512807    -0.410411
25      -0.017022    -1.097043      0.783811    -0.410411
26      -0.017022    -0.047241      0.783811     1.455095
27       0.550371     0.215209      0.207479    -0.410411
28       0.550371    -0.047241     -0.368852    -0.410411
29      -0.868111    -0.572142      0.783811    -0.410411
..            ...          ...           ...          ...
120      0.490659     0.700782      0.268167     0.997633
121     -1.553753    -0.539541     -1.181385    -0.094666
122      1.748759    -0.539541      2.080107    -0.094666
123     -0.452916    -0.849621     -1.181385    -0.822865
124      0.176134     1.010863      0.268167     0.269434
125      0.962446     0.700782      0.811749    -0.822865
126     -0.610178    -0.539541     -1.362579    -0.822865
127     -0.767441     0.080621     -1.181385    -0.822865
128     -0.295653    -0.539541      0.086973     0.269434
129      0.962446     0.080621      0.449361    -1.551065
130      1.276971    -0.539541      0.992943    -0.458766
131      2.063284     2.561267      1.536525    -0.094666
132     -0.295653    -0.539541      0.086973     0.633533
133     -0.452916    -0.539541     -0.818997    -1.915164
134     -0.767441    -1.159702      0.086973    -2.279264
135      1.748759     0.080621      0.992943     0.997633
136     -0.452916     1.320944      0.086973     1.361733
137     -0.295653     0.390702     -0.094221    -0.822865
138     -0.924703     0.080621     -1.362579    -0.822865
139      0.490659     0.390702     -0.275415     0.269434
140      0.176134     0.390702      0.086973     1.361733
141      0.490659     0.390702     -0.818997     0.997633
142     -1.239228    -0.849621     -0.818997    -0.458766
143      0.333396     0.700782      0.630555     0.997633
144      0.176134     1.010863      0.268167     1.725833
145      0.176134     0.080621     -0.637803     0.997633
146     -0.452916    -1.469783     -1.000191    -0.458766
147     -0.138391     0.080621     -0.637803    -0.094666
148     -0.610178     1.320944     -0.275415     0.997633
149     -1.081966     0.080621     -0.818997    -0.822865

[150 rows x 4 columns]

## Apply - Combine Operations

### Filter Techniques

http://pandas.pydata.org/pandas-docs/stable/groupby.html#filtration

Important points to remember from the documetation:

* The filter method returns a subset of the original object
* The argument of filter must be a function that, applied to the group as a whole, returns True or False
* For dataframes with multiple columns, filters should explicitly specify a column as the filter criterion

In [41]:
irisgroup.describe()

                  sepal_length  sepal_width  petal_length  petal_width
species
setosa     count     50.000000    50.000000     50.000000    50.000000
           mean       5.006000     3.418000      1.464000     0.244000
           std        0.352490     0.381024      0.173511     0.107210
           min        4.300000     2.300000      1.000000     0.100000
           25%        4.800000     3.125000      1.400000     0.200000
           50%        5.000000     3.400000      1.500000     0.200000
           75%        5.200000     3.675000      1.575000     0.300000
           max        5.800000     4.400000      1.900000     0.600000
versicolor count     50.000000    50.000000     50.000000    50.000000
           mean       5.936000     2.770000      4.260000     1.326000
           std        0.516171     0.313798      0.469911     0.197753
           min        4.900000     2.000000      3.000000     1.000000
           25%        5.600000     2.525000      4.000000     1.200000
           50%        5.900000     2.800000      4.350000     1.300000
           75%        6.300000     3.000000      4.600000     1.500000
           max        7.000000     3.400000      5.100000     1.800000
virginica  count     50.000000    50.000000     50.000000    50.000000
           mean       6.588000     2.974000      5.552000     2.026000
           std        0.635880     0.322497      0.551895     0.274650
           min        4.900000     2.200000      4.500000     1.400000
           25%        6.225000     2.800000      5.100000     1.800000
           50%        6.500000     3.000000      5.550000     2.000000
           75%        6.900000     3.175000      5.875000     2.300000
           max        7.900000     3.800000      6.900000     2.500000

In [51]:
def maxfilter(x):
    if np.max(x['sepal_length']) > 6:
        return True
    else : 
        return False
    
filtered = irisgroup.filter(maxfilter)

filtered.head(5)

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [49]:
type(filtered)

pandas.core.frame.DataFrame

In [50]:
filtered.groupby('species').describe()

                  petal_length  petal_width  sepal_length  sepal_width
species
versicolor count     50.000000    50.000000     50.000000    50.000000
           mean       4.260000     1.326000      5.936000     2.770000
           std        0.469911     0.197753      0.516171     0.313798
           min        3.000000     1.000000      4.900000     2.000000
           25%        4.000000     1.200000      5.600000     2.525000
           50%        4.350000     1.300000      5.900000     2.800000
           75%        4.600000     1.500000      6.300000     3.000000
           max        5.100000     1.800000      7.000000     3.400000
virginica  count     50.000000    50.000000     50.000000    50.000000
           mean       5.552000     2.026000      6.588000     2.974000
           std        0.551895     0.274650      0.635880     0.322497
           min        4.500000     1.400000      4.900000     2.200000
           25%        5.100000     1.800000      6.225000     2.800000
           50%        5.550000     2.000000      6.500000     3.000000
           75%        5.875000     2.300000      6.900000     3.175000
           max        6.900000     2.500000      7.900000     3.800000